<?php
// DO NOT EDIT MANUALLY
// 
// generated by sqlgg 20200521-12-g67a70a6+M on 2020-12-08T21:41Z

require('db.php');
$db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
$db->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_NUM);

header('Content-type', 'application/json');
try
{
  if (!isset($_GET['_name'])) die('{"error": "missing parameter"}');
  else if ($_GET['_name'] == "list")
  {
    $stm = $db->prepare("SELECT * FROM results");
    $stm->execute();
    echo '[';
    $first = true;
    while ($row = $stm->fetch())
    {
      if (!$first) echo ',';
      echo json_encode(array("name" => is_null($row[0]) ? null : $row[0], "grade" => is_null($row[1]) ? null : (float)$row[1]));
      $first = false;
    }
    echo ']';
  } // list
  else if ($_GET['_name'] == "update")
  {
    $stm = $db->prepare("UPDATE results SET grade=? WHERE name=?");
    $stm->bindValue(1, isset($_POST["grade"]) ? (float)$_POST["grade"] : null);
    $stm->bindValue(2, isset($_POST["name"]) ? $_POST["name"] : null);
    $stm->execute();
    echo json_encode(array('count' => $stm->rowCount()));
  } // update
  else if ($_GET['_name'] == "insert")
  {
    $stm = $db->prepare("INSERT INTO results(name, grade) VALUES (?, ?)");
    $stm->bindValue(1, isset($_POST["name"]) ? $_POST["name"] : null);
    $stm->bindValue(2, isset($_POST["grade"]) ? (float)$_POST["grade"] : null);
    $stm->execute();
    echo json_encode(array('count' => $stm->rowCount()));
  } // insert
  else echo('{"error": "invalid parameter"}');
}
catch (Exception $e)
{
  echo '{"error": "internal error"}';
}
